(in-package :fiendish-rl)

(defun color-from-hsv (h s v)
  (declare (optimize (safety 0) (speed 3) (debug 0))
           (single-float s v)
           ((signed-byte 16) h))
  (loop while (< h 0) do (setf h (+ h 360)))           
  (let* ((c (* v s))
         (x (* c (- 1 (abs (- (mod (/ h 60) 2) 1)))))
         (m (- v c)))
    (case (floor (/ h 60))
      (0 (values (+ c m) (+ x m) m))
      (1 (values (+ x m) (+ c m) m))
      (2 (values m (+ c m) (+ x m)))
      (3 (values m (+ x m) (+ c m)))
      (4 (values (+ x m) m (+ c m)))
      (5 (values (+ c m) m (+ x m))))))
